---
- name: Backup de configuração pfSense (contorno checksum)
  hosts: pfsenseloja      # ajuste para seu host no Inventário
  gather_facts: no

  tasks:
    - name: Criar pasta de backup local (AWX)
      local_action:
        module: file
        path: "./backups"
        state: directory

    - name: Copiar config.xml para /tmp no pfSense
      raw: cp /cf/conf/config.xml /tmp/config-{{ inventory_hostname }}.xml

    - name: Baixar o config.xml sem validação de checksum
      fetch:
        src: /tmp/config-{{ inventory_hostname }}.xml
        dest: "./backups/{{ inventory_hostname }}-config.xml"
        flat: yes
        validate_checksum: no

    - name: Remover arquivo temporário no pfSense
      raw: rm /tmp/config-{{ inventory_hostname }}.xml
