---
- name: Backup de configuração pfSense (via raw cat)
  hosts: pfsenseCondominios            # seu grupo de pfSense
  gather_facts: no

  tasks:
    - name: Garantir pasta de backups no host AWX
      delegate_to: localhost
      ansible.builtin.file:
        path: /var/lib/awx/projects/pfsense-backup/backups
        state: directory

    - name: Ler config.xml diretamente do pfSense
      raw: cat /cf/conf/config.xml
      register: config_raw
      changed_when: false

    - name: Gravar o config.xml no host AWX
      delegate_to: localhost
      ansible.builtin.copy:
        dest: /var/lib/awx/projects/pfsense-backup/backups/{{ inventory_hostname }}-config.xml
        content: "{{ config_raw.stdout }}"
