---
- name: Backup de configuração pfSense via base64
  hosts: pfsenseloja        # ajuste para seu host no Inventory
  gather_facts: no

  tasks:
    - name: Criar pasta de backup local (no AWX)
      local_action:
        module: file
        path: "./backups"
        state: directory

    - name: Ler config.xml e codificar em base64 no pfSense
      raw: base64 /cf/conf/config.xml
      register: config_b64
      changed_when: false

    - name: Gravar o config.xml decodificado localmente
      local_action:
        module: copy
        content: "{{ config_b64.stdout | b64decode }}"
        dest: "./backups/{{ inventory_hostname }}-config.xml"
