---
- name: Backup de configuração pfSense via base64
  hosts: pfsenseCondominios       # ← roda em todos os membros do grupo
  gather_facts: no

  tasks:
    - name: Criar pasta de backup persistente no host AWX
      delegate_to: localhost
      file:
        path: /var/lib/awx/projects/pfsense-backup/backups
        state: directory

    - name: Ler config.xml codificado em base64 no pfSense
      raw: base64 /cf/conf/config.xml
      register: config_b64
      changed_when: false

    - name: Gravar o config.xml decodificado no host AWX
      delegate_to: localhost
      copy:
        content: "{{ config_b64.stdout | b64decode }}"
        dest: "/var/lib/awx/projects/pfsense-backup/backups/{{ inventory_hostname }}-config.xml"
